/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface AppHome {
    'AICLient': any;
    'answer': string;
    'question': string;
  }
  interface AppProfile {
    'name': string;
  }
  interface AppRoot {}
  interface DialogHistory {
    'DialogHistoryText': string[];
  }
}

declare global {


  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {}
  var HTMLAppProfileElement: {
    prototype: HTMLAppProfileElement;
    new (): HTMLAppProfileElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLDialogHistoryElement extends Components.DialogHistory, HTMLStencilElement {}
  var HTMLDialogHistoryElement: {
    prototype: HTMLDialogHistoryElement;
    new (): HTMLDialogHistoryElement;
  };
  interface HTMLElementTagNameMap {
    'app-home': HTMLAppHomeElement;
    'app-profile': HTMLAppProfileElement;
    'app-root': HTMLAppRootElement;
    'dialog-history': HTMLDialogHistoryElement;
  }
}

declare namespace LocalJSX {
  interface AppHome {
    'AICLient'?: any;
    'answer'?: string;
    'question'?: string;
  }
  interface AppProfile {
    'name'?: string;
  }
  interface AppRoot {}
  interface DialogHistory {
    'DialogHistoryText'?: string[];
  }

  interface IntrinsicElements {
    'app-home': AppHome;
    'app-profile': AppProfile;
    'app-root': AppRoot;
    'dialog-history': DialogHistory;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'app-home': LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
      'app-profile': LocalJSX.AppProfile & JSXBase.HTMLAttributes<HTMLAppProfileElement>;
      'app-root': LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
      'dialog-history': LocalJSX.DialogHistory & JSXBase.HTMLAttributes<HTMLDialogHistoryElement>;
    }
  }
}


